### ISSUE TITLE
Look at how to integrate with Terraform as an external data provider

### ISSUE THREAD

**Issue by beddari** [jerakia/python-jerakia#10]
This library might be a good starting point https://github.com/operatingops/terraform_external_data

**Comment by hhenkel** [comment]
Not sure why this is a topic for the python lib? Shouldn't it be a datasource in jerakia?

**Comment by jonandernovella** [comment]
I worked on a simple demo to provide this functionality, precisely based on that decorator: https://github.com/jonandernovella/terraform-jerakia

**Comment by beddari** [comment]
Closing this, the golang integration is a better path.
